version: "3.2"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: deathstaradmin
    container_name: DeathStarAdmin
    volumes:
      - ./app:/var/www/html
    ports:
      - 8080:80
